### ISSUE TITLE
Adding support for TransportClient on local node

### ISSUE THREAD

**Issue by wiibaa** [tlrx/elasticsearch-test#1]
Hello,
first thanks for your library, it really makes elasticsearch unit testing a breeze.
My use case is similar to the one described here: 
http://codestepping.blogspot.fr/2010/09/elastic-search-unit-testing-with-local.html

As it is not so obvious for newbie, maybe you could support it with a new annotation, what do you think ??

Thanks

**Comment by tlrx** [comment]
Hi,

Sounds good, I already plan to add a @ElasticsearchTransportClient annotation and I'll check to integrate your use case :)
