### ISSUE TITLE
Consider a solution without using @RunWith()

### ISSUE THREAD

**Issue by itsadok** [tlrx/elasticsearch-test#11]
Sometimes it is impossible to use the RunWith annotation. For example, when you're already using it for parameterized tests, or when writing unit tests for Play Framework. I had both problems.

Using EsSetup was not an option for me either, because I needed a Client object to inject into my code.

Eventually I did the following:

```
LocalClientProvider provider = new LocalClientProvider();
provider.open();
Client client = provider.client();

// (inject client into code and perform tests)

provider.close()
```

If this is the recommended way to do this, you should document it.

**Comment by tlrx** [comment]
You can do something like:

<pre>
EsSetup esSetup = new EsSetup();
esSetup.countAll();
Client client = esSetup.client();
// Use the client
esSetup.terminate();
</pre>

At least one request execution is needed to really open the client. This could be fixed in future version.
