### ISSUE TITLE
DeleteAll doesn't delete

### ISSUE THREAD

**Issue by Chris2048** [tlrx/elasticsearch-test#13]
For some reason when I execute 'DeleteAll', it doesn't delete everything in EL, is this how it works? I should mention my EL server is not running locally, if that matters.

**Comment by tlrx** [comment]
Could you provide some code or gist to reproduce please?

**Comment by Chris2048** [comment]
Sorry, it was my fault, I wasn't passing it the client.

**Comment by tlrx** [comment]
No pb :)
