### ISSUE TITLE
publish snapshot versions on sonatype?

### ISSUE THREAD

**Issue by bclozel** [tlrx/elasticsearch-test#17]
Hello. Me again.

Could you publish a snapshot on sonatype for the latest version?
[Your snapshot repo on sonatype](https://oss.sonatype.org/content/repositories/snapshots/com/github/tlrx/) is currently empty.

A `mvn clean deploy` should publish a snapshot, given you have your sonatype credentials in your maven settings file.

Thanks!

**Comment by johanpoirier** [comment]
:+1:

**Comment by JulienColin** [comment]
:+1:

**Comment by tlrx** [comment]
Done!
