### ISSUE TITLE
Add @ElasticsearchIndex support for external mappings file(s)

### ISSUE THREAD

**Issue by btiernay** [tlrx/elasticsearch-test#19]
Much like what is available for in `@ElasticsearchIndex`'s `settingsFile` attribute. This is very useful when a project is using externalized mapping files.

**Comment by btiernay** [comment]
Really great project btw!

**Comment by tlrx** [comment]
Please have a look at https://github.com/tlrx/elasticsearch-test/issues/4#issuecomment-24678085
