### ISSUE TITLE
EsSetup test with multiple @Test methods fails with NoShardAvailableException

### ISSUE THREAD

**Issue by btiernay** [tlrx/elasticsearch-test#20]
On the second test I get a `NoShardAvailableException`. Is this to be expected? Your `EsSetupTest` has only one test case so its hard to tell if it is an error on my end.

Thanks!

**Comment by btiernay** [comment]
This may be related to https://github.com/tlrx/elasticsearch-test/issues/18 .

**Comment by tlrx** [comment]
Hi,

Can you give a gist to reproduce the bug? Thanks.

**Comment by btiernay** [comment]
Hmm, seems to work now. Closing this issue
