### ISSUE TITLE
Most of the time test fails with: Failed to execute phase [query_fetch], all shards failed

### ISSUE THREAD

**Issue by didlich** [tlrx/elasticsearch-test#26]
Hi,

I noticed a strange behavior if using EsSetup for my UnitTests. I've created a simple Maven project with one test executed 6 times with setUp and tearDown after each test. The most of the time at least one of the test methods fails (may need some runs).
I am not sure if this is really a problem with the test framework, but may be some one has a hint to solve the problem.

Link to the maven project: https://docs.google.com/file/d/0B6hsQXmR9ZrsNkZweDQ1UEFvNW8/edit?usp=sharing

**Comment by tlrx** [comment]
Hum, looks strange. I'll try to run your test project asap too see if I can reproduce this issue.

**Comment by didlich** [comment]
Hi, thanks for the quick response. It seems there other people have similar problem with their test setup:

http://elasticsearch-users.115913.n3.nabble.com/Undeterministic-quot-total-failure-quot-when-running-my-test-suite-td4036300.html

I followed the advice to use the Health-API to monitor the creation of my index.

``` java
        ClusterHealthResponse actionGet = esSetup.client().admin().cluster()
                .health(
                        Requests.clusterHealthRequest()
                        .waitForYellowStatus()
                        .waitForEvents(Priority.LANGUID)
                        .waitForRelocatingShards(0)
                        .indices(new String[]{tenantsIndex}))                
                .actionGet();
        if (actionGet.isTimedOut() == true) {
            log.error("ElasticSearch-Node got Timeout");
        }
```

this seems to solve the problem. After 10 runs there are no test errors.
I think in my case it has to do with the setUp+tearDown after each test method run. Things are asynchronous if doing:

``` ruby
esSetup.execute(
                deleteAll(),
                createIndex("empty_index"),
                createIndex(tenantsIndex)
                .withSettings(settings)
                );
```

therefore we need to wait until the index is created.

I will observe the tests and hope the problem is solved.
