### ISSUE TITLE
client() on LocalClientProvider does not instantiate a Node

### ISSUE THREAD

**Issue by richtmat** [tlrx/elasticsearch-test#28]
I'm using elasticsearch-test in the context of CDI and in my tests I want to inject the client into my beans. I wrote a @Produces method which calls esSetup.client(). My problem is that client() does not call open() to start a node. Is that intended behaviour?

In my fork I'm calling open() in client() - I can prepare a PR if you like..

**Comment by tlrx** [comment]
Hi,

When using CDI frameworks, consider using https://github.com/tlrx/elasticsearch-test/blob/master/src/main/java/com/github/tlrx/elasticsearch/test/provider/DefaultClientProvider.java instead of LocalClientProvider. Thus you'll be able to use your own Client instance.
