### ISSUE TITLE
BulkLoading, last line is forgiven (if the file hasn't a final \n)

### ISSUE THREAD

**Issue by gpolaert** [tlrx/elasticsearch-test#32]
If there is no \n at the end of file, the last document isn't loading into the index.
I use 

```
    clusterSetup.execute(
                deleteAll(),
                createIndex("log-fake")
                        .withData(fromClassPath("app/indexing/postfix.json")));

```

**Comment by tlrx** [comment]
This is how elasticsearch works, see http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-bulk.html#docs-bulk
