### ISSUE TITLE
Any plan to release the test for elasticsearch 1.2.1 ?

### ISSUE THREAD

**Issue by samuraraujo** [tlrx/elasticsearch-test#38]

**Comment by phjardas** [comment]
+1

**Comment by phjardas** [comment]
I've just submitted pull request #39 for ElasticSearch 1.2.1

**Comment by tlrx** [comment]
@samuraraujo @phjardas Done! Check https://oss.sonatype.org/content/repositories/releases/com/github/tlrx/elasticsearch-test/1.2.1/

**Comment by phjardas** [comment]
Cheers!
