### ISSUE TITLE
Support for Templates

### ISSUE THREAD

**Issue by wiibaa** [tlrx/elasticsearch-test#4]
We are currently using index templates file in our main elasticsearch env.

We would like to reuse these template file within elasticsearch-test for consistency.
A new annotation with a settingFile to be handled by calling IndicesAdminClient templates related methods would be great.

**Comment by synhershko** [comment]
+1

I was thinking of having this as a parameter "template" on the @ElasticsearchClient attribute.

**Comment by tlrx** [comment]
Issue linked to #19 

Hi guys,

Sorry for the delay. I really encourage people to use EsSetup class over annotations like @ElasticsearchClient.

Using annotations was my first idea, but it does not fit well with the JUnit Runner (the class that executes JUnit tests) and are really painful to maintain.

By the way, pull request are greatly appreciated :)

**Comment by btiernay** [comment]
What about a JUnit rule?
