### ISSUE TITLE
Valid JSON data

### ISSUE THREAD

**Issue by Vadi** [tlrx/elasticsearch-test#45]
The [data json file](https://github.com/tlrx/elasticsearch-test/blob/master/src/test/resources/com/github/tlrx/elasticsearch/test/data/products.json)  is not a valid JSON data structure.

We have a situation that we need to produce data dynamically. What about introducing array or something to make JSON structure a valid one. Or may be I am missing something here.

**Comment by tlrx** [comment]
This file is in the Elasticesearch Bulk API format.

See http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-bulk.html#docs-bulk
