### ISSUE TITLE
Central Repository

### ISSUE THREAD

**Issue by obazoud** [tlrx/elasticsearch-test#5]
Could you upload this artifact to the central repository or OSS repository ?

Thanks

http://maven.apache.org/guides/mini/guide-central-repository-upload.html
https://oss.sonatype.org/content/groups/public

**Comment by tlrx** [comment]
Hi,

I'll upload to the Central rep or OSS next week.

I will also commit some new functionnalities.

## 

Bonjour Olivier,

Je le ferai, mais pas avant la semaine prochaine car je suis en
déplacement. J'en profiterai pour ajouter qques fonctionnalités non
commitees.

-- Tanguy
@tlrx

Le mardi 25 septembre 2012, Olivier Bazoud a écrit :

> Could you upload to the central repository or OSS repository ?
> 
> Thanks
> 
> http://maven.apache.org/guides/mini/guide-central-repository-upload.html
> https://oss.sonatype.org/content/groups/public
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tlrx/elasticsearch-test/issues/5.

## 

## 

Tanguy Leroux
tanguy.leroux@zenika.com
Tél: 06 28 55 17 87

**Comment by neowulf** [comment]
Hello!

I would very much like to use this artifact but can't be found in the repository:

https://oss.sonatype.org/index.html#nexus-search;quick~elasticsearch-test

Could you please confirm if this has been uploaded? If in fact, the artifact has been uploaded, can you please provide the repository snippet that needs to be defined in the pom.xml?

Thanks!

**Comment by derryos** [comment]
Same issue as neowulf33, can't find in any repository. Currently manually adding after downloading the src and building (although only getting 0.0.4-SNAPSHOT on pull?)

**Comment by tlrx** [comment]
@derryos @neowulf33 @obazoud Sorry guys for the late reply - the Maven config has been done but the lib is not present in OSS repo yet. I still need to have some rights in the Sonatype OSS repo.

I'll ping you as soon as the lib is in the repo.

**Comment by derryos** [comment]
Thanks for that. Spotted this this morning on OSS

<dependency>
  <groupId>com.github.tlrx</groupId>
  <artifactId>elasticsearch-test</artifactId>
  <version>0.0.5-SNAPSHOT</version>
</dependency>

but now getting compilation errors so have switched back to my own
0.0.4-SNAPSHOT,

Derry

**Comment by tlrx** [comment]
elasticsearch-test-0.0.5 is now available in OSS repository.

@derryos What kind of compilation errors? The only breaking change is on ElasticsearchTransportClient which can't be local anymore (it was a bad idea to implement local on this object).

**Comment by derryos** [comment]
My bad:
fr.tlrx.elasticsearch.test=>com.github.tlrx.elasticsearch.test!

Now works perfectly.

Also, thanks for the headsup on local in ESTransportClient (and for the
very useful library!)

**Comment by neowulf** [comment]
Thanks!
